export const SORT_BY_DELIVERY_TIME = "SORT_BY_DELIVERY_TIME";
export const SORT_BY_RATING = "SORT_BY_RATING";
export const SORT_BY_COST_ASCENDING = "SORT_BY_COST_ASCENDING";
export const SORT_BY_COST_DESCENDING = "SORT_BY_COST_DESCENDING";
export const SORT_BY_RELEVANCE = "SORT_BY_RELEVANCE";
